print("Hello guys")
print("my name is Luka")
print("I love programming")
print("its my seecond best thing to do")
print("its really cool here")
print("Life is great")
print("and also Life is short")
print("so enjoy it")
print("Live your life")
print("and love god")
print("Im 12 years old")
print("Im also a football player")
print("its my dream to make it pro")
print("i hope i make it")
print("I love GOA")
print("Its the best Programming academy in the world")
print("Pretty cool")
print("I also love playing other sports too")
print("And yeah")
print("Thats it")
print("Print")
print("Playing")
print("football")
print("Football")
print("magic")
print("youtube")
print("Niko")
print("amazing")
print("idk")
print("What")
print("to")
print("Type")
print("type")
print("youtubers")
print("gamers")
print("printing")
print("Kinda")
print("boring")
print("goa")
print("youtube channel")

print(8 + 10)
print(12 - 5)
print(12 * 25)
print(10 / 2)
print(100 // 50)